---
swagger: "2.0"
info:
  version: "2023-05-28T12:39:56Z"
  title: "d-id"
basePath: "/prod"
schemes:
- "https"
paths:
  /talks:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "DIDUserCheck"
        required: true
        schema:
          $ref: "#/definitions/DIDUserCheck"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-request-validator: "本文の検証"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:xxxxxxxxxxxxx:function:d-id_talks/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /talks/create:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RocketChatTokenCheck"
        required: true
        schema:
          $ref: "#/definitions/RocketChatTokenCheck"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-request-validator: "本文の検証"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:xxxxxxxxxxxxxx:function:d-id_prompt/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  RocketChatTokenCheck:
    type: "object"
    required:
    - "token"
    properties:
      token:
        $ref: "#/definitions/RocketChatToken"
  DIDUSer:
    type: "string"
    enum:
    - "xxxxxxxxxxxxxx"
  RocketChatToken:
    type: "string"
    enum:
    - "xxxxxxxxxxxxx"
  DIDUserCheck:
    type: "object"
    properties:
      token:
        $ref: "#/definitions/DIDUSer"
x-amazon-apigateway-request-validators:
  本文の検証:
    validateRequestParameters: false
    validateRequestBody: true
