AWSTemplateFormatVersion: "2010-09-09" 
Resources:
  SourceEvent:
    Properties:
      Description: >-
        Rule for Amazon CloudWatch Events to detect changes to the source
        repository and trigger the pipeline
      EventPattern:
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceName:
            - main
          referenceType:
            - branch
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join 
            - ':'
            - - 'arn:aws:codecommit'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - Fn::ImportValue: "CodeCommitRepoExportParameter"
        source:
          - aws.codecommit
      Name: !Join 
        - '-'
        - - !Ref 'AWS::StackName'
          - SourceEvent
      State: ENABLED
      Targets:
        - Arn: !Join 
            - ':'
            - - arn
              - aws
              - codepipeline
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - Ref: 'AWS::StackName'
          Id: ProjectPipelineTarget
          RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CloudWatchEventRule_Role
    Type: 'AWS::Events::Rule'
  ReleasePipeline:
      Type: "AWS::CodePipeline::Pipeline"
      Properties:
        Name: "releasePipeline"
        ArtifactStore:
          Location: !ImportValue "ArtifactsBucketExportParameter"
          Type: S3
        RoleArn: !ImportValue "CodePipelineTrustRoleARNExportParameter"
        Stages:
          - Name: Source
            Actions:
              - ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: CodeCommit
                  Version: '1'
                Configuration:
                  BranchName: main
                  PollForSourceChanges: false
                  RepositoryName: 
                    Fn::ImportValue: "CodeCommitRepoExportParameter"
                InputArtifacts: []
                Name: ApplicationSource
                OutputArtifacts:
                  - Name: lab6-SourceArtifact
                RunOrder: 1
          - Name: Static_Check
            Actions:
              - ActionTypeId:
                  Category: Invoke
                  Owner: AWS
                  Provider: Lambda
                  Version: '1'
                Configuration:
                  FunctionName:
                    Fn::ImportValue: "CFNValidateLambdaExportParameter"
                  UserParameters: !Sub
                    - '{"input": "lab6-SourceArtifact", 
                    "file": "cloudformation/application.json",
                    "output": "${labBucket}"}'
                    - labBucket: !ImportValue ArtifactsBucketExportParameter
                InputArtifacts:
                  - Name: lab6-SourceArtifact
                OutputArtifacts:
                  - Name: TemplateSource2
                Name: stack_validate
                Region: !Ref 'AWS::Region'
                RunOrder: 1
          - Name: Build
            Actions:
              - ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: '1'
                Configuration:
                  ProjectName: Lab6-BuildProject
                InputArtifacts:
                  - Name: lab6-SourceArtifact
                Name: Build
                OutputArtifacts:
                  - Name: lab6-BuildArtifact
                RunOrder: 1
          - Name: Test_Stack
            Actions:
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  ChangeSetName: test-stack-changeset
                  ParameterOverrides: '{"Stage":"Test"}'
                  RoleArn: !ImportValue "CloudFormationTrustRoleARNExportParameter"
                  StackName: lab6-test-stack
                  TemplatePath: lab6-BuildArtifact::cloudformation/application.json
                InputArtifacts:
                  - Name: lab6-BuildArtifact
                Name: GenerateChangeSet
                OutputArtifacts: []
                RunOrder: 1
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  ChangeSetName: test-stack-changeset
                  StackName: lab6-test-stack
                InputArtifacts: []
                Name: DeployChangeSet
                OutputArtifacts: []
                RunOrder: 2
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CodeDeploy
                  Version: '1'
                Configuration:
                  ApplicationName: lab6-Application
                  DeploymentGroupName: lab6-test-stack-DeploymentGroup
                InputArtifacts:
                  - Name: lab6-BuildArtifact
                Name: Deploy
                OutputArtifacts: []
                RunOrder: 3
          - Name: Approval
            Actions:
              - ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: '1'
                Configuration:
                  CustomData: >-
                    Do you want to purge Test region resources and initiate
                    Production deployment ?
                InputArtifacts: []
                Name: Purge_Test
                OutputArtifacts: []
                Region: !Ref 'AWS::Region'
                RunOrder: 1
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                Configuration:
                  ActionMode: DELETE_ONLY
                  RoleArn: 
                    !ImportValue "CloudFormationTrustRoleARNExportParameter"
                  StackName: lab6-test-stack
                InputArtifacts: []
                Name: Delete_Test_Stack
                OutputArtifacts: []
                Region: !Ref 'AWS::Region'
                RunOrder: 2
          - Name: Prod_Stack
            Actions:
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  ChangeSetName: prod-stack-changeset
                  ParameterOverrides: '{"Stage":"Prod"}'
                  RoleArn: 
                    !ImportValue "CloudFormationTrustRoleARNExportParameter"
                  StackName: lab6-prod-stack
                  TemplatePath: lab6-BuildArtifact::cloudformation/application.json
                InputArtifacts:
                  - Name: lab6-BuildArtifact
                Name: GenerateChangeSet
                OutputArtifacts: []
                RunOrder: 1
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: '1'
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  ChangeSetName: prod-stack-changeset
                  StackName: lab6-prod-stack
                InputArtifacts: []
                Name: DeployChangeSet
                OutputArtifacts: []
                RunOrder: 2
              - ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CodeDeploy
                  Version: '1'
                Configuration:
                  ApplicationName: lab6-Application
                  DeploymentGroupName: lab6-prod-stack-DeploymentGroup
                InputArtifacts:
                  - Name: lab6-BuildArtifact
                Name: Deploy
                OutputArtifacts: []
                RunOrder: 3
